blueprint:
  name: Awtrix light Yahoo Stock Information
  description: Push Yahoo Stock Information to Awtrix light
  author: Thomas michelnet.ch
  domain: automation
  input:
    awtrix_device:
      name: Awtrix light
      description: Select the Awtrix light
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX Light
          multiple: false

    basetopic:
      name: Basetopic
      description: Basetopic is only nessery if you have a special mqtt topic configured on the Awtrix
      default: "Device"
      selector:
        text:

    share_provider:
      name: Share
      description: Select the Share infos from Yahoo Finance
      selector:
        entity:
          integration: "yahoofinance"
          multiple: true

    text_color_delimiter:
      name: Delimiter Text Color
      description: Select the Text color
      selector:
        color_rgb:
      default: [255, 255, 255]


    text_color_share_plus:
      name: Color Postiv
      description: Select the Text color postiv
      selector:
        color_rgb:
      default: [0, 255, 0]

    text_color_share_minus:
      name: Color Negativ
      description: Select the Text color negativ
      selector:
        color_rgb:
      default: [255,0 ,0]


    push_icon:
      name: Push Icon
      description: Icon behavior
      selector:
        select:
          options:
            - label: "Icon doesn't move"
              value: "0"
            - label: "Icon moves with text and will not appear again"
              value: "1"
            - label: "Icon moves with text but appears again when the text starts"
              value: "2"
          mode: dropdown
      default: "0"

    duration:
      name: Duration (in seconds)
      description: Sets how long the app should be displayed. 0 is global app time.
      default: "0"
    lifetime:
      name: Lifetime (in seconds)
      description: Sets how long the app should stay alive before it gets removed from the app cycle automatically. 0 is infinite lifetime.
      default: "0"
    position:
      name: Position
      description: Position in the Awtrix cycle
      default: 0
      selector:
        number:
          min: 0
          max: 20
    appname:
      name: Appname
      description: Appname
      default: "stock"
      selector:
        text:





variables:
  awtrix: !input awtrix_device
  share: !input share_provider
  basetopic_text : !input basetopic
  basetopic: >
    {%- if (basetopic_text)!="Device" -%}
    {{basetopic_text}}
    {% else %}
    {{ iif( device_attr(awtrix, 'name_by_user') != none, device_attr(awtrix, 'name_by_user'), device_attr(awtrix, 'name') ) }}
    {%- endif -%}


  push_icon: !input push_icon
  duration: !input duration
  lifetime: !input lifetime
  appname: !input appname
  pos: !input position

  text_color_delimiter: !input text_color_delimiter
  color_delimiter: >
    {{ "#%02x%02x%02x" | format(text_color_delimiter[0], text_color_delimiter[1], text_color_delimiter[2]) }}


  #share
  text_color_share_minus: !input text_color_share_minus
  color_minus: >
    {{ "#%02x%02x%02x" | format(text_color_share_minus[0], text_color_share_minus[1], text_color_share_minus[2]) }}


  text_color_share_plus: !input text_color_share_plus
  color_plus: >
    {{ "#%02x%02x%02x" | format(text_color_share_plus[0], text_color_share_plus[1], text_color_share_plus[2]) }}



  text: >

    {% for i in range(0, share | count ) %}
    {
    "t": "{{state_attr(share[i], 'symbol').split('.')[0]+" "+ state_attr(share[i], 'regularMarketChangePercent') | string +"%" }}",
    "c": "{% if state_attr(share[i], 'trending')=="down"  %}{{color_minus}}{%- else -%}{{color_plus}} {%- endif -%}"
    }
    {% if i<(share |count)-1  %}
    ,{
    "t": " - ",
    "c": "{{color_delimiter}}"
    },
    {%- endif -%}
    {% endfor%}


trigger:
  - platform: state
    entity_id: !input share_provider
    id: Changes
    enabled: true

action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "{{basetopic}}/custom/{{appname}}"
      payload: >
        { 
          "pos": {{pos}},  
          "text":[{{text}}],
          "icon": "stock",
          "pushIcon": "{{ push_icon }}",
          "duration": "{{ duration }}",
          "lifetime": "{{ lifetime }}"
        }
